import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Single autogenerated sidebar; ordering comes from _category_.json files
// and per-doc sidebar_position front matter.
const sidebars: SidebarsConfig = {
  docs: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
